# Generated by Django 3.2.7 on 2021-09-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='SettingsImg/Logo', verbose_name='Logo')),
                ('phoneNumber', models.CharField(blank=True, max_length=14, null=True, verbose_name='Numéro de téléphone')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse email')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Localisation')),
                ('actif', models.BooleanField(default=False, unique=True)),
                ('slide', models.ImageField(blank=True, null=True, upload_to='SettingsImg/Slide', verbose_name='Slide1')),
                ('showSlide', models.TextField(blank=True, null=True)),
                ('promotion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Promotion1')),
            ],
        ),
    ]
