# Generated by Django 3.2.7 on 2021-09-05 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='showSlide',
            new_name='saveOtherImg',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='actif',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='location',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='slide',
        ),
        migrations.AddField(
            model_name='settings',
            name='dateBorn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Localisation'),
        ),
        migrations.AddField(
            model_name='settings',
            name='languages',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lieu de résidence'),
        ),
        migrations.AddField(
            model_name='settings',
            name='mainImg',
            field=models.ImageField(blank=True, null=True, upload_to='Person/mainImg', verbose_name='Slide1'),
        ),
        migrations.AddField(
            model_name='settings',
            name='otherImg',
            field=models.ImageField(blank=True, null=True, upload_to='Person/otherImg', verbose_name='Slide1'),
        ),
        migrations.AddField(
            model_name='settings',
            name='placeBorn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lieu de naissance'),
        ),
        migrations.AddField(
            model_name='settings',
            name='residence',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lieu de résidence'),
        ),
        migrations.AddField(
            model_name='settings',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
