# Generated by Django 3.2.7 on 2021-09-05 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20210905_1429'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='UserRegistration',
        ),
    ]
