# Generated by Django 3.2.7 on 2021-09-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_rename_settings_userregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='dateBorn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='languages',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Langue parlée'),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='mainImg',
            field=models.ImageField(blank=True, null=True, upload_to='Person/mainImg', verbose_name='Image principale'),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='otherImg',
            field=models.ImageField(blank=True, null=True, upload_to='Person/otherImg', verbose_name='Autres images'),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
