# Generated by Django 3.2.7 on 2021-09-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20210910_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='slug',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
