# Generated by Django 3.2.7 on 2021-09-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_userregistration_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='todo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
