# Generated by Django 3.2.7 on 2021-09-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_userregistration_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('slide', models.ImageField(blank=True, null=True, upload_to='settings/slides', verbose_name='Image slide')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
