# Generated by Django 3.2.7 on 2021-09-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_slides'),
    ]

    operations = [
        migrations.AddField(
            model_name='slides',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
