# Generated by Django 3.2.7 on 2021-09-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_auto_20210914_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivecommand',
            name='status',
            field=models.CharField(default='ouvert', max_length=15),
        ),
    ]
