# Generated by Django 3.2.7 on 2021-09-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0015_auto_20210915_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='slides',
            name='indexImg',
            field=models.ImageField(blank=True, null=True, upload_to='settings/shortView', verbose_name='Image Bas de slide'),
        ),
    ]
