# Generated by Django 3.2.7 on 2021-09-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0016_slides_indeximg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slides',
            options={'verbose_name_plural': 'Slides'},
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='longAboutUs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='pictureAboutUs',
            field=models.ImageField(blank=True, null=True, upload_to='settings/about', verbose_name='Image A propos de nous'),
        ),
    ]
