# Generated by Django 3.2.7 on 2021-09-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0018_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
