# Generated by Django 3.2.7 on 2021-09-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0020_auto_20210916_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.BooleanField(default='non lu'),
        ),
    ]
