# Generated by Django 3.2.7 on 2021-09-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0021_alter_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(default='non lu', max_length=15),
        ),
    ]
