# Generated by Django 2.2.20 on 2021-10-22 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0024_auto_20211022_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistration',
            old_name='chlildren',
            new_name='children',
        ),
    ]
