# Generated by Django 2.2.20 on 2021-11-15 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0027_userregistration_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punctuation', models.IntegerField(blank=True, null=True)),
                ('adaptation', models.IntegerField(blank=True, null=True)),
                ('respect', models.IntegerField(blank=True, null=True)),
                ('iniative', models.IntegerField(blank=True, null=True)),
                ('finalNote', models.IntegerField(blank=True, null=True)),
                ('userId', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('profileUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.UserRegistration')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
