# Generated by Django 3.2.7 on 2021-09-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='SettingsImg/Logo', verbose_name='Logo')),
                ('slide1', models.ImageField(blank=True, null=True, upload_to='SettingsImg/Logo', verbose_name='Slide1')),
                ('slide2', models.ImageField(blank=True, null=True, upload_to='SettingsImg/Logo', verbose_name='Slide2')),
                ('slide3', models.ImageField(blank=True, null=True, upload_to='SettingsImg/Logo', verbose_name='Slide3')),
                ('phoneNumber', models.CharField(blank=True, max_length=14, null=True, verbose_name='Numéro de téléphone')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse email')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Localisation')),
            ],
            options={
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
    ]
