# Generated by Django 3.2.7 on 2021-09-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_settings_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='actif',
            field=models.BooleanField(default=False),
        ),
    ]
