# Generated by Django 3.2.7 on 2021-09-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_settings_actif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='actif',
            field=models.BooleanField(default=False, unique=True),
        ),
    ]
