# Generated by Django 3.2.7 on 2021-09-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210903_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='slide1',
            field=models.ImageField(blank=True, null=True, upload_to='SettingsImg/Slide', verbose_name='Slide1'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='slide2',
            field=models.ImageField(blank=True, null=True, upload_to='SettingsImg/Slide', verbose_name='Slide2'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='slide3',
            field=models.ImageField(blank=True, null=True, upload_to='SettingsImg/Slide', verbose_name='Slide3'),
        ),
    ]
