# Generated by Django 3.2.7 on 2021-09-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210903_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='promotion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Promotion'),
        ),
    ]
