# Generated by Django 3.2.7 on 2021-09-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_settings_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('promotion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Promotion')),
            ],
        ),
        migrations.RemoveField(
            model_name='settings',
            name='promotion',
        ),
    ]
