# Generated by Django 3.2.7 on 2021-09-12 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210903_1753'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promotion',
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
